### ISSUE TITLE
Not scraping images

### ISSUE THREAD

**Issue by pplusp** [alxpnt2/PlexJav18.bundle#10]
Appreciate the new update bringing metadata scraping back online but, for some reason, the plugin hasn't been able to scrape images for months.

Not sure if this is an R18 api thing, but would it be possible to implement other sources such as JavLibrary as well?  Might also help in finding metadata for de-listed titles as well.

**Comment by alxpnt2** [comment]
I just pushed a large update that should resolve the current issue preventing images from loading. For titles not on R18, 141JAV is now used as a backup so usually getting some metadata and a poster is now possible for those titles.

Unfortunately, JavLibrary has a lot of features that make it difficult to scrape. It has the most complete database that I've found, but I haven't found a way to access it from a plex plug-in.

**Comment by pplusp** [comment]
Thanks for the speedy update! [biscuitrainbow](https://github.com/biscuitrainbow) created a forked version some months ago that was scraping from both JavLibrary and 141, but they seem to have deleted it.  May be worth reaching out to them for some advice?

**Comment by alxpnt2** [comment]
I checked the version of biscuitrainbow's fork that I had downloaded, and it looks like it was actually scraping javdatabase, not JavLibrary. I just added javdatabase support to this plug-in as well, but JavLibrary still seems out of reach.
