### ISSUE TITLE
Only scrapping front and back cover

### ISSUE THREAD

**Issue by Kaikhong** [alxpnt2/PlexJav18.bundle#12]
Since last week the agent only scrape the front and back cover, so that plex only displays the middle section of the cover. I tried with other site such as 141 or javguru, onejav and all of them gave the same results. Do you have any idea? and its seem movies specific, it could be a problem from the servers

**Comment by alxpnt2** [comment]
Unfortunately, for technical reasons, I had to build a separate web service to cut out the front half of the posters to display in Plex, and that service was running for free on Heroku. However, Heroku stopped providing free services on 12/1, so now I have to migrate that service somewhere else. I'm looking into it now, but until I get it up and running again the posters will look strange.

**Comment by alxpnt2** [comment]
I just pushed a new update that should resolve this issue. Just refresh the metadata on the titles with incorrect posters, and it should get the front poster now. You might also have to manually edit the titles to switch the poster from the old one to the new one.
