### ISSUE TITLE
Jav Guru seems to have gone down

### ISSUE THREAD

**Issue by pplusp** [alxpnt2/PlexJav18.bundle#13]
Not sure if there's been a change with Jav Guru's site that's broken the agent, but it seems to have stopped scraping metadata from Jav Guru recently.

**Comment by alxpnt2** [comment]
Unfortunately, it seems like JavGuru has updated to try to prevent software like this from scraping data from it. I'll try to get it working again but I may have to find other sites to parse data from.

**Comment by JustynLim** [comment]
Would it be possible to scrap metadata from javlibrary?

> Unfortunately, it seems like JavGuru has updated to try to prevent software like this from scraping data from it. I'll try to get it working again but I may have to find other sites to parse data from.

**Comment by alxpnt2** [comment]
Sadly, javlibrary has all the same anti-bot protections that javguru has. It's too bad because it has by far the most complete database.

**Comment by JustynLim** [comment]
> Sadly, javlibrary has all the same anti-bot protections that javguru has. It's too bad because it has by far the most complete database.

I happened to gone through other repositories and found one database which should solve the issue but I lack the experience in changing the source myself 

They are currently using R18.dev: https://github.com/jvlflame/Javinizer/issues/350#issuecomment-1368173951

After making several queries for recently released films, I can say that the catalog for this site is quite extensive. Could you please look into it?

**Comment by alxpnt2** [comment]
That site seems very promising. I'll look into integrating it this weekend.

**Comment by alxpnt2** [comment]
R18.dev is now supported. Hopefully this means we no longer need JavGuru.

**Comment by JustynLim** [comment]
> R18.dev is now supported. Hopefully this means we no longer need JavGuru.

Thanks for the alert. I've been waiting for this. Hopefully everything works out

**Comment by JustynLim** [comment]
After refreshing metadata, I found 2 issues so far: 
1) Several codes from my collection cannot be matched (metadata not found even though the code exists on R18.dev's db)

2) The scraper generates low res actresses' avatar taken from the internet (instead of the one available from the site)

Any idea on what is causing the issue?

**Comment by alxpnt2** [comment]
If you give me some example codes for either of these issues, I can look into why they might not be working.

**Comment by JustynLim** [comment]
These are just a few from my collection that are experiencing this issue. Don't get me wrong though, it works fine majority of the time. The list is just lengthy as I'm trying to keep track of future improvements
ACZD-083
ACZD-092
ACZD-006
BUG-004
DFET-009
DFET-015
DMBA-172
DMBA-190
DMBA-184
DMBA-188
DMBJ-052
DMBK-052
DMBL-008
EMSK-008
GUN-771

**Comment by alxpnt2** [comment]
I just pushed a fix for R18.dev's search. I tried several of the titles you listed and all of the ones I tested are now matching for me now.

**Comment by JustynLim** [comment]
Could you specify which codes have you tried? I've already tried majority of them and have yet to obtain a match

**Comment by alxpnt2** [comment]
I tried ACZD-083, BUG-004, DFET-009, DMBA-172, DMBK-052, and GUN-771 and didn't have trouble with them after yesterday's update. If you're still not getting any results, then I might need you to send me your log (instructions on the front page).

**Comment by JustynLim** [comment]
lmk if I gave you the wrong one
[com.plexapp.agents.jav18.log](https://github.com/alxpnt2/PlexJav18.bundle/files/11185918/com.plexapp.agents.jav18.log)

**Comment by alxpnt2** [comment]
It looks like Plex is still running the old version of the plug-in. I recommend reinstalling it and trying again.

**Comment by JustynLim** [comment]
Found the issue. I had a duplicate plugin in the same plugin. Thanks for helping out
