### ISSUE TITLE
Not finding some titles even though I can find them in R18.dev

### ISSUE THREAD

**Issue by besmirch0** [alxpnt2/PlexJav18.bundle#14]
Hello Team,

This is now my go to Plex agent. Thanks for this.

I encountered issues where the agent would not find metadata even though I can manually search the titles in R18.dev.

Few examples would be STARS-576 and MXGS-1221. I tried to fix match in Plex using the title, content ID and DVD ID but still no luck.

Any thoughts?

**Comment by alxpnt2** [comment]
I just pushed a fix that should make R18.dev search more reliable. Those two titles seem to be working for me now.

**Comment by besmirch0** [comment]
Thank you! That worked!
