### ISSUE TITLE
Jav18 does not scrape any metadata (Windows 10-11)

### ISSUE THREAD

**Issue by NoFace33** [alxpnt2/PlexJav18.bundle#15]
Hello,

For some reason, the JAV18 agent does not work as it designs on my PLEX server.

Since a few months ago, it just stops completely, i.e., no titles, no cover, no actress information, no year, etc. I updated the .bundle to the latest edition and nothing has changed. I used the "match" function (for several movies) in plex and no results/match being were being found. I have updated the plex server (v4.100.1). All the movies searched are present in the ressources scrapped.

 Can you provide any guidance about how to solve this problem? Here's the plugin's log.
[com.plexapp.agents.jav18.log](https://github.com/alxpnt2/PlexJav18.bundle/files/11245041/com.plexapp.agents.jav18.log)

Thank you!

**Comment by alxpnt2** [comment]
It looks like there's an SSL error whenever the plugin tries to connect to the internet. I'm not sure what could cause that, but it seems like an issue with your plex environment. Do your other plex plugins work?

**Comment by NoFace33** [comment]
> It looks like there's an SSL error whenever the plugin tries to connect to the internet. I'm not sure what could cause that, but it seems like an issue with your plex environment. Do your other plex plugins work?

All the default Plex agents, HTTP Anidb Metadata Agent (HAMA), Plex Anime Multi Source Agent (AMSA) and `https://github.com/Xavier-Lam/JAV.bundle` all works fine.

I even tried to setup a new instance of plex on my VM. Same result

**Comment by NoFace33** [comment]
Just updated another of my agent (AMSA v(1.0.7.3](https://github.com/Dingmatt/AMSA/releases/tag/V1_0_7_3) and it mentions that Plex might have broken its SSL component. IDK if it might give an inkling as to what is happening but it sure looks promising.

**Comment by NoFace33** [comment]
After looking more into it it does seems to be a plex [issue](https://github.com/Dingmatt/AMSA/issues/43) : "One of the undocumented changes Plex made with 1.32.X is [they dropped OpenSSL 1.1.1 support](https://forums.plex.tv/t/ssl-became-broken-after-latest-pms-update/837416/4) , so now it's OpenSSL 3+ only. It really sucks because Plex uses Python 2.7 which doesn't have OpenSSL 3. I've asked about any plans to include python3 but worried that this might be the end of plugins."

**Comment by alxpnt2** [comment]
Thanks for finding this info for me. After updating plex server to v1.32.1.6999, does the plugin work for you again?

**Comment by NoFace33** [comment]
> Thanks for finding this info for me. After updating plex server to v1.32.1.6999, does the plugin work for you again?

Yes it does work now
