### ISSUE TITLE
Look like the plugin is not working in the past few days?

### ISSUE THREAD

**Issue by gniy19** [alxpnt2/PlexJav18.bundle#16]
Look like the plugin is not working in the past few days.
I try to match many new JAV but it's always error

**Comment by alxpnt2** [comment]
It's still working for me. Can you post your log? Instructions are on the front page.

**Comment by gniy19** [comment]
thanks! here's the log file
[com.plexapp.agents.jav18.log](https://github.com/alxpnt2/PlexJav18.bundle/files/11302332/com.plexapp.agents.jav18.log)

**Comment by gniy19** [comment]
All the default Plex agents work fine

**Comment by alxpnt2** [comment]
It looks like this is the same issue as #15. I'm going to have to do some research on how to solve this, since I'm not able to duplicate it.

**Comment by alxpnt2** [comment]
Are you running plex in a virtual machine?

**Comment by gniy19** [comment]
I use it on my PC windows 10.
I just happened only 3-4 days ago before that it was fine

**Comment by alxpnt2** [comment]
It looks like this might be a plex issue that is fixed in plex server version v1.32.1.6999. Do you mind updating your server to that version and test to see if it works again?

**Comment by SControl07** [comment]
Hello developer I have the same issue. Copied everything to PLEX plugin folder. JAV18 agent shows up in settings. But it is not detecting anything when scanning JAV folder. 

PLEX server shows up-to date status Version 1.32.0.6973. Do not see version 1.32.1.6999 download option.

**Comment by alxpnt2** [comment]
https://www.plex.tv/media-server-downloads/

Here's the link for the update. It looks like it's in beta right now, so I believe you have to upgrade manually.
