### ISSUE TITLE
The plugin can't pick Gravure movie metadata from R18.dev

### ISSUE THREAD

**Issue by mikiway-git** [alxpnt2/PlexJav18.bundle#19]
Hello, here is a recent log. Everything work with JAV movies, only Gravure doesn't work.
The name is updating and look like this : [R18.dev] [BFAA-073] To You After 8 Years / Anju Kozuki (Blu-ray Disc)
<img width="947" alt="Capture d’écran 2023-06-09 à 09 39 32" src="https://github.com/alxpnt2/PlexJav18.bundle/assets/129160517/6707535a-640b-44a8-a1b7-9bbed77826b4">

[com.plexapp.agents.jav18.log](https://github.com/alxpnt2/PlexJav18.bundle/files/11703594/com.plexapp.agents.jav18.log)

**Comment by alxpnt2** [comment]
I just pushed a fix for this, let me know if you still have issues.

**Comment by mikiway-git** [comment]
It works ! Thank you for this amazing plugin.
