### ISSUE TITLE
Multiple versions on same video

### ISSUE THREAD

**Issue by raenoll** [alxpnt2/PlexJav18.bundle#2]
How can I manage multiple versions like 1080p and 4k of the same video?
No search if appendix is added.

**Comment by raenoll** [comment]
I renamed to 
XXX-123.mp4
XXX-123.mkv
as a temporary solution.

**Comment by alxpnt2** [comment]
This is a general Plex question, not specific to this plugin. Here's a guide for one potential solution: https://support.plex.tv/articles/200381043-multi-version-movies/
