### ISSUE TITLE
Can't match if DVD ID not present in R18.dev

### ISSUE THREAD

**Issue by besmirch0** [alxpnt2/PlexJav18.bundle#20]
Hi there,

I am able to find the following content IDs in R18.dev but the plugin does not match it. Common factor is that they don't have DVD IDs. I tried matching by inputting the full content ID but it is not matching. Any advise?

Sample IDs are:
1akdl00222
1silks00100
ipbz00001
ipbz00002

**Comment by alxpnt2** [comment]
Titles without DVD IDs should be fixed now. Let me know if you still have issues.

**Comment by besmirch0** [comment]
Yup, it works now. Thanks!
