### ISSUE TITLE
[R18.dev] Error trying to update metadata

### ISSUE THREAD

**Issue by jarderiu** [alxpnt2/PlexJav18.bundle#21]
The R18.dev metadata agent works consistently bar a number of titles such as:
`24ID-056,
 24ID-027,
 CESD-398,
 EMU-075,
 TOMN-072`

The agent seems to fail after/during actor search
see logs attached
[com.plexapp.agents.jav18.log](https://github.com/alxpnt2/PlexJav18.bundle/files/11858091/com.plexapp.agents.jav18.log)

**Comment by alxpnt2** [comment]
This should be fixed now. Let me know if you still have issues.
