### ISSUE TITLE
Tagging Errors | Fails To Update Database

### ISSUE THREAD

**Issue by llabons** [alxpnt2/PlexJav18.bundle#23]
[jav18.log](https://github.com/alxpnt2/PlexJav18.bundle/files/12270139/jav18.log)

In the attached log you will see FSDSS-610 and 611 attempt to be tagged. 

611 is tagged correctly and updates the "Cast" entry in XML as it should. For some reason 610 fails despite the correct Cast data being found from jav database and javguru.

In the Fix Match menu the correct information is displayed but it fails to write to the plex metadata. Attempted to force correct tagging by making a new Library and limiting the matches to those two sources, issue persists.

PMS v1.32.1.6999
Plex for Windows v1.75.0.3920-8b50876d

**Comment by alxpnt2** [comment]
I fixed an issue with the JavDatabase scraper so it should be able to get role data from there again. You're also getting an error with R18.dev scraping that I'm not getting, so hopefully just downloading the current update and trying again will fix that.

**Comment by llabons** [comment]
Installed the current version and all galleries with missing information (as reported) were tagged. Bug squashed.
