### ISSUE TITLE
Posters are not being scraped, all other metadata is

### ISSUE THREAD

**Issue by qwerty8713** [alxpnt2/PlexJav18.bundle#24]
[com.plexapp.agents.jav18.log.txt](https://github.com/alxpnt2/PlexJav18.bundle/files/12384324/com.plexapp.agents.jav18.log.txt)

Posters are not being uploaded. All other metadata is being populated correctly. What am I doing wrong

If that is not the correct log file, please let me know.

**Comment by alxpnt2** [comment]
Strange, when I try this title, it does get a poster for me. Try updating the plug-in and refreshing the metadata again.

**Comment by qwerty8713** [comment]
By update, do I just download and copy the bundle again?

**Comment by alxpnt2** [comment]
Yeah, just re-install on top of your existing plug-in.
