### ISSUE TITLE
Other data with the same name is loaded.

### ISSUE THREAD

**Issue by dioarame** [alxpnt2/PlexJav18.bundle#25]
Thanks for making such a great agent available!
However, I'm having a bit of trouble using it, which is why I'm raising this issue.
For example, there is an issue when there are pieces with the same numbering.
Here is the case I am experiencing.
I want to match "ABF-009 - Soaked Sexual Intercourse That Was Broken Until The Rookie Teacher Was Completely Fallen Wet See-Through NTR Asuna Kawai" released in 2023,
the agent matches 'ABF-009: Blow Job Instruction Book vol. 6', which was released in 2011.
As it turns out, searching for ABF-009 in r18dev leads directly to the 2011 item. However, in the JAVdatabase, only an entry from 2023 exists.
To compensate for this, we tried tweaking the checks in the agent's working source and retried, but found that it either failed to read or kept matching to items from 2011. This seems to be an overall issue with the ABF series.

That said, the problem I'm having is that R18dev has a very high priority, even with the agent's source unchecked. Any suggestions on how to resolve this?

* I have already tried the following methods. [example is ABF-009, as above].
- With R18dev unchecked, check av-wiki.
  -> I was able to find and select the correct entry, but after the metadata work, the entry was from 2011.
- Entered 118abf00009, 118abf009r, 118abf009, which are the contentIDs of the example ABF-009.
  -> often didn't work, and if it did, the item was created as a 2011 item after metadata operations.
- If we wanted to use it for R18dev only, we needed to completely rename it. In this example, renaming it to 'FTKABF-009' allowed the metadata to be written normally. However, this would break the numbering and would not be appropriate.
- Searching with only JABDatabase checked yielded no results, and this was true for the other entries as well.

**Comment by dioarame** [comment]
Sorry to keep commenting. I tried matching with [AV-wiki] and found that the [Av-wiki] prefix does not disappear after matching. This was the case for Prestige Premium labels like the 200GANA series and others. When this happened, the bundle only pulled the title as information.
Example) 200GANA-1548.mp4 -> [AV-Wiki] [200GANA-1548] 百戦錬磨のナンパ師のヤリ部屋 ...
However, if the material in AV-wiki was also in R18.dev, this worked fine, but with the same problem of matching the work that was viewed first.

**Comment by alxpnt2** [comment]
Hi, sorry for the late replay. I just pushed a fix that should hopefully solve your issues. After updating, you'll need to temporarily enable the "Use the Content ID instead of the DVD ID to search" plug-in setting, then search using a content ID that R18.dev recognizes for your video ("118abf009r" in this case). The correct title should appear in the search results, and it should update with the correct metadata. Once it's been updated, you should disable the "Use the Content ID" setting since only R18.dev will be able to provide metadata while it's enabled.

Let me know if you still have issues.
