### ISSUE TITLE
Can't use in Plex on Synology.

### ISSUE THREAD

**Issue by XpredatorV** [alxpnt2/PlexJav18.bundle#4]
Can't use in Plex on Synology. Plex version: 1.18.5.2309-f5213a238. It does not appear Jav18, i couldn't select. Not visible, i have others plugins and working, but I can't use this one.

**Comment by alxpnt2** [comment]
I don't use Synology and have no idea why this plugin in particular wouldn't work with it.

**Comment by besmirch0** [comment]
This actually works in Synology. I use Synology. It won't appear if you just unzip and rename in the file to .bundle as most Plex plugins. You need to unzip and then transfer the JAV18.bundle to your File Station.
