### ISSUE TITLE
Stopped scraping most information

### ISSUE THREAD

**Issue by pplusp** [alxpnt2/PlexJav18.bundle#6]
Not sure if this agent is being monitored at all anymore, but it's stopped scraping most information except the title.  I don't know what might have caused this; perhaps R18 has updated their site and broken links to various database parameters?

**Comment by stivify** [comment]
I got the same issue too. R18 updated their site and cannot scrape the folder image and most information. Is there a better way to do it now since this isnt working anymore?

**Comment by biscuitrainbow** [comment]
I created the folk version for this plugin to make it work again by changing site from R18.com to javdatabase and 141Jav. I think it's not good as this one but it's worked for me.  

https://github.com/biscuitrainbow/PlexJav18.bundle

**Comment by pplusp** [comment]
Appreciate the fork @biscuitrainbow! It seems to work mostly well, though there are a few titles I've noticed the agent unable to find, even though they're listed in javdatabase (e.g. DV-1233, ABP-606, MXGS-624).  Since it seems like @alxpnt2 has abandoned the agent entirely, would love to get a fix from yours.

**Comment by alxpnt2** [comment]
The plug-in has been updated to use R18's API instead of scraping their site, which no longer works.
