### ISSUE TITLE
Jav18 does not scrape any metadata  in PLEX server (on a QNAP NAS)

### ISSUE THREAD

**Issue by xiaopv** [alxpnt2/PlexJav18.bundle#9]
Hello,

For some reason, the JAV18 agent does not work as it designs on my PLEX server. 

I started to use it about a year ago. It worked well initially (get the cover, metadata, etc.), but after a while, it would only get the title (no cover, no actress information, no year, etc.) Then after a while, it just stops completely, i.e., titles were not even being updated. I updated the .bundle to the latest edition and nothing has changed. I used the "match" function (for several movies) in plex and no results/match being were being found. I have updated the plex server (on a qnap server) to the latest edition. Can you provide any guidance about how to solve this problem?

Thank you!

**Comment by jasonjan2003** [comment]
A trailing slash needs to be manually appended to the search URL as generated here:

https://github.com/alxpnt2/PlexJav18.bundle/blob/3449bdc971ee40df5a9174f20b953e6cd324a45d/Jav18.bundle/Contents/Code/__init__.py#L37

At some point the website started to 404 requests without the trailing slash...

**Comment by alxpnt2** [comment]
This should be fixed now.
